const r = require('express').Router();
const c = require('../controllers/requestController');
const requireRole = require('../common/roles');
r.post('/', c.request);
r.get('/', c.list);
r.post('/:id/approve', requireRole(['staff', 'admin']), c.approve);
r.post('/:id/reject', requireRole(['staff', 'admin']), c.reject);
r.post('/:id/issue', requireRole(['staff', 'admin']), c.issue);
r.post('/:id/return', requireRole(['staff', 'admin']), c.return);
module.exports = r;
